apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-reporter
  labels:
    jmeter_mode: reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: reporter
  template:
    metadata:
      labels:
        jmeter_mode: reporter
    spec:
      containers:
        - name: jmreporter
          image: kubernautslabs/jmeter-reporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8686
